@startuml Jeu
title Jeu

' =====================
' Config défaut
' =====================
class Config {
    + port: int
    + ipAddress: string
    + maxPlayers: int
    + pointsToGive: int
    + baseEnergy: int
    + maxEnergy: int
}

' =====================
' Jeu
' =====================

enum GameStatus {
    WAITING_FOR_PLAYER
    WAITING_FOR_PLAYER_CONFIG
    WAITING_FOR_HOST_CONFIG
    PLAYING
    END_GAME
}

enum GameAction {
    ATTACK
    DEFENSE
    ATTACK_PUISSANCE
    RECHARGE
}

class Message {
    + type: MessageType
    + action: GameAction
    + status: GameStatus
    + data: string
}


class RobotConfig {
    - hpPoints: int
    - armorPoints: int
    - damagePoints: int
    + RobotConfig(hpPoints: int, armorPoints: int, damagePoints: int)
    + isValid(pointsToGive: int): boolean
}

class GameFactory {
    - isHost: boolean
    + createGame(config: Config): void
    + joinGame(): void
    + configurePlayer(config: RobotConfig): void
    + configureHost(config: RobotConfig): void
    + executeAction(action: GameAction): Message
    + getGameStatus(): GameStatus
    + onMessageReceived(message: Message, from: Player): void
}




' =====================
' Dictionnaire
' =====================
enum MessageType {
    PLAYER_JOIN
    ROBOT_READY
    PLAYER_ACTION
    PLAYER_RESULT
    PLAYER_LEAVE
    PLAYER_REPLAY
    QUIT
}

class MessageHelper {
    + buildMessage(type: MessageType, action: GameAction, status: GameStatus, data: string): Message
    + parseMessage(message: string): Message
}

class CommandDictionary {
    + {static} CREATE: string = "CREATE"
    + {static} JOIN: string = "JOIN"
    + {static} ROBOT: string = "ROBOT H A D"
    + {static} ACTION: string = "ACTION"
    + {static} RESULT: string = "RESULT {MESSAGE}"
    + {static} REPLAY: string = "REPLAY"
    + {static} LEAVE: string = "LEAVE"
    + {static} QUIT: string = "QUIT"
    + {static} getCommand(type: MessageType): string
    + {static} getMessageType(command: string): MessageType
}


' =====================
' Connexion Socket
' =====================

class SocketServer {
    - port: int
    + startServer(port: int): void
    + stopServer(): void
}

class SocketClient {
    - ipAddress: string
    - port: int
    + connectToServer(ipAddress: string, port: int): void
    + exit(): void
    + isConnected(): boolean
}

class "ConnectionHandler : IDisposable" {
    - socket: Socket
    + input: InputStream
    + output: OutputStream
    + sendMessage(message: Message): void
    + receiveMessage(): Message
}

' =====================
' Vue
' =====================

interface IGameView {
    + askPlayerType(): string
    + showMessage(message: string): void
    + showWinner(player: Player): void
    + askPlayerConfig(): RobotConfig
    + askPlayerAction(): GameAction
    + askPlayerReplay(): boolean
}

class ConsoleView {
    + askPlayerType(): string
    + showMessage(message: string): void
    + showWinner(player: Player): void
    + askPlayerConfig(): RobotConfig
    + askPlayerAction(): GameAction
    + askPlayerReplay(): boolean
}

class Player {
    - isHost: boolean
    - isReady: boolean
    + name: string
    + confirmIsReady(): void
    + createRobot(config: RobotConfig): void
}

class Game {
    - id: string
    - status: GameStatus
    - currentPlayer: int
    - players: List<Player>
    + addPlayer(player: Player): void
    + removePlayer(player: Player): void
    + startGame(): void
    + checkGameEnded(): boolean
    + getWinner(): Player
}

enum StatsType {
    HP
    ATTACK
    DEFENSE
    ENERGY
}

class Stats {
    - type: StatsType
    - baseValue: int
    - currentValue: int
}

class Robot {
    - isRecharging: boolean
    - isDefending: boolean
    + attack(): int
    + attackWithPower(): int
    + recharge(): void
    + receiveDamage(damage: int): int
    + getStats(stats: StatsType): string
}



' =====================
' Handler Message reçu
' =====================


interface ICommand {
    + handle(message: Message, from:Player): void
}

class PlayerJoinHandler {
    + handle(message: Message, from:Player): void
}
class RobotReadyHandler {
    + handle(message: Message, from: Player): void
}
class PlayerActionHandler {
    + handle(message: Message, from: Player): void
}
class PlayerResultHandler {
    + handle(message: Message, from: Player): void
}
class PlayerLeaveHandler {
    + handle(message: Message, from: Player): void
}
class PlayerReplayHandler {
    + handle(message: Message, from: Player): void
}
class QuitHandler {
    + handle(message: Message, from: Player): void
}

class CommandMenu {
    - handlers: Map<MessageType, ICommand>
    + addHandler(type: MessageType, handler: ICommand): void
    + execute(message: Message, from: Player): void
}



' =====================
' Relations
' =====================
Game "1" o-- "1" Config
Game "1" -- "2" Player
Player "1" *-- "1" Robot
Robot "1" *-- "4" Stats
Stats "*" -- "1" StatsType
IGameView <|.. ConsoleView
GameFactory "1" *-- "1" Game
GameFactory "1" o-- "0..1" SocketServer
GameFactory "1" o-- "0..1" SocketClient
GameFactory "1" -- "1" IGameView
GameFactory "1" *-- "1" CommandMenu
SocketServer "1" o-- "*" "ConnectionHandler : IDisposable"
SocketClient "1" o-- "1" "ConnectionHandler : IDisposable"
MessageHelper ..> CommandDictionary
MessageHelper ..> Message
Player "1" -- "1" RobotConfig
Player "1" o-- "0..1" "ConnectionHandler : IDisposable"

ICommand "1" --> "1" Game
ICommand "1" --> "0..1" IGameView
ICommand <|.. PlayerJoinHandler
ICommand <|.. RobotReadyHandler
ICommand <|.. PlayerActionHandler
ICommand <|.. PlayerResultHandler
ICommand <|.. PlayerLeaveHandler
ICommand <|.. PlayerReplayHandler
ICommand <|.. QuitHandler
CommandMenu "1" o-- "*" ICommand
@enduml